### ISSUE TITLE
W30 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#14]
# W30, BDK Library Dev Call
:calendar: Tues July 19, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel 

## Discussion Items

- [x] [`bdk` `0.20.0`](https://github.com/bitcoindevkit/bdk/releases/tag/v0.20.0) Released! 🎉 + examples in tweet thread 
- [x] Draft notes directly in GitHub
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] nourou: "Banxaas : A p2p bitcoin exchange" Sénégal

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] csralvall: Move change logic to coin_select [#630](https://github.com/bitcoindevkit/bdk/pull/630)
- [x] danielabrozzoni: Allow signing only specific leaf hashes [#645](https://github.com/bitcoindevkit/bdk/pull/645)
- [x] evanlinjin:  Multi descriptor: Decouple transaction building logic [#647](https://github.com/bitcoindevkit/bdk/pull/647)
- [x] evanlinjin:  Multi descriptor: Introduce DatabaseFactory trait [#654](https://github.com/bitcoindevkit/bdk/pull/654)
- [x] csralvall: Consolidate fee_amount and amount_needed [#662](https://github.com/bitcoindevkit/bdk/pull/662)
- [x] danielabrozzoni: Various fixes to the fee_amount calculation in create_tx [#666](https://github.com/bitcoindevkit/bdk/pull/666) 
- [x] vladimirfomene:Add testing on Compact Block filters in CI [#668](https://github.com/bitcoindevkit/bdk/pull/668)
- [x] evanlinjin:  Introduce get_checksum_bytes method and improvements [#671](https://github.com/bitcoindevkit/bdk/pull/671)
- [x] evanlinjin:  Fix wallet sync not finding coins of addresses which are not cached [#672](https://github.com/bitcoindevkit/bdk/pull/672)
- [x]  oleonardolima: feature: add block height checkpoint feature, and add reorganization handling [#10](https://github.com/oleonardolima/block-events/pull/10) 

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] rajarshimaitra: Satoshi's Calculator. [#102](https://github.com/bitcoindevkit/bdk-cli/pull/102)
  
## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] rajarshimaitra: [Refactor] Move tutorials from Blog to Tutorial section [#103](https://github.com/bitcoindevkit/bitcoindevkit.org/issues/103)
- [x] BitcoinZavior: Add bdk-rn blogpost [#107](https://github.com/bitcoindevkit/bitcoindevkit.org/issues/107)
- [x] vladimirfomene: Update installation and interface guide of CLI [#109](https://github.com/bitcoindevkit/bitcoindevkit.org/issues/109) 

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9

**Comment by evanlinjin** [comment]
It will be good to have https://github.com/bitcoindevkit/bdk/pull/671 as these changes will be good for #647 and #654 (in my opinion), but I guess we will find out in the call whether these changes make sense :)

**Comment by evanlinjin** [comment]
I also think I just fixed #521 in this PR: https://github.com/bitcoindevkit/bdk/pull/672

May be a good idea to include this in the meeting since I see it is a high-priority bug in the roadmap.

**Comment by notmandatory** [comment]
Thanks @evanlinjin I added your latest PRs, the last one with the electrum sync might be impacted by the work @LLFourn is doing with [bdk_core](https://bitcoindevkit.org/blog/bdk-core-pt1/).

**Comment by evanlinjin** [comment]
> Thanks @evanlinjin I added your latest PRs, the last one with the electrum sync might be impacted by the work @LLFourn is doing with [bdk_core](https://bitcoindevkit.org/blog/bdk-core-pt1/). 

Thank you for pointing this out! I had a brief look at the work done on `bdk_core`, and from my understanding, this bug is not addressed there (and it should have some sort of feedback so that we can implement a similar feedback mechanism around it).

Currently, to sync with `bdk_core`, you pass a list of `scriptPubKey`s to the Blockchain client alongside a `stop_gap`, returning an `Update` object.

https://github.com/LLFourn/bdk_core_staging/blob/67d1e5499b0eb1de59f652c433c88942646593b3/bdk_esplora/src/ureq.rs#L167

The `Update` object conveniently contains a `last_active_index` field. However, it may also be helpful to contain "the last script index looked at". This way, using the stop gap, last active index and last index looked at, we can determine the number of additional scripts to search for in order to satisfy "stop gap".

If I am not wrong, I would assume that this PR should work well with `bdk_core` (if the suggested feedback is provided). But maybe @LLFourn can provide some more insight.

**Comment by evanlinjin** [comment]
I just realized that I maybe should have communicated with the team before trying to tackle the ticket, so I would like to apologize for that and I'll make sure I do so next time.
