### ISSUE TITLE
W32 BDK Library Team Call 

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#16]
:calendar: Tues August 2, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel 

## Discussion Items

- [x] [Release 0.21.0 feature freeze](https://github.com/bitcoindevkit/bdk/milestone/19) tomorrow August 3rd
- [x] [Tab Conf](https://2022.tabconf.com/), Oct 12-15 in Atlanta, GA, USA
- [x] Need help with LDK-BDK integration See [#65] and [#490]
       - need to create esplora crate with ureq and async features with calls needed by LDK
       - make sure electrum crate also covers calls needed by LDK
       - implement LDK traits using esplora and electrum and future blockchain traits extracted from bdk
- [x] LLFourn, evanlinjin, rajarshimaitra, justinmoon, bdk_core + fedimint collaboration meeting in Kuala Lumpur
- [x]  rajarshimaitra, new every other Thur call to talk about compact block filter module improvements
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

[#65]: https://github.com/bitcoindevkit/bdk/issues/65
[#490]: https://github.com/bitcoindevkit/bdk/pull/490

## New Projects and Support

- [x] [Ord](https://github.com/casey/ord) @rodarmor
- [x] [Bitmask](https://github.com/diba-io/bitmask-core) @josediegorobles @cryptoquick

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] danielabrozzoni: Various fixes to the fee_amount calculation in create_tx [#666](https://github.com/bitcoindevkit/bdk/pull/666)
- [x] afilini: Fix the early InsufficientFunds error in the branch and bound [#693](https://github.com/bitcoindevkit/bdk/pull/693)
- [x] csralvall: Consolidate fee_amount and amount_needed [#662](https://github.com/bitcoindevkit/bdk/pull/662)
- [x] evanlinjin: Fix wallet sync for RpcBlockchain [#683](https://github.com/bitcoindevkit/bdk/pull/683)
    - Needed for [#640](https://github.com/bitcoindevkit/bdk/pull/640) Get balance in categories
- [x] vladimirfomene: Implement conversion for Lightning fee rate [#678](https://github.com/bitcoindevkit/bdk/pull/678)
   - This one is not in the milestone, so plz review the other ones first!

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] rajarshimaitra:  Satoshi's Calculator. [#102](https://github.com/bitcoindevkit/bdk-cli/pull/102)
- [x] rajarshimaitra:  Update crate documentation [#104](https://github.com/bitcoindevkit/bdk-cli/pull/104)

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] rajarshimaitra: [Refactor] Move tutorials from Blog to Tutorial section [#103](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/103)

<br>

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9

**Comment by vladimirfomene** [comment]
Hello @notmandatory , can we add https://github.com/bitcoindevkit/bdk/pull/678 to review begs?

**Comment by danielabrozzoni** [comment]
> Hello @notmandatory , can we add https://github.com/bitcoindevkit/bdk/pull/678 to review begs?

Added to the top PRs, with a comment saying to review the ones in the milestone first :)

I've updated the comment with the top BDK PRs, I haven't inserted the BDK-CLI and doc ones as I'm not really working on those projects, and I'm not sure which PRs are top priority...
