### ISSUE TITLE
W34 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#18]
:calendar: Tues August 16, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel 

## Discussion Items

- [x] [Release 0.21.0](https://github.com/bitcoindevkit/bdk/releases/tag/v0.21.0) 🎉 with [awesome tweet thread](https://twitter.com/bitcoindevkit/status/1558115668913946625?t=loqHV_8WkVx5INHI-_I9Cg&s=19)
- [x] LDK entopy [discussion on ff-bindings](https://discord.com/channels/753336465005608961/824249944810192956/1008865813958230057)
- [x] Summer of Bitcoin mentees wrapping up
- [x] "Optech Make Me Famous!" label
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] [BDK-LDK Integration](https://github.com/orgs/bitcoindevkit/projects/13) project
- [x] anything else new?

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] notmandatory:  Update DEVELOPMENT_CYCLE.md to work with [patch.crates-io] [#544](https://github.com/bitcoindevkit/bdk/issues/544)
- [x]  terror: Add allow_dust method to TxBuilder [#689](https://github.com/bitcoindevkit/bdk/issues/689)
- [x]  wszdexdrf: Add a custom signer for hardware wallets [#682](https://github.com/bitcoindevkit/bdk/issues/682)
- [x]  vladimirfomene: Implement conversion for Lightning fee rate [#678](https://github.com/bitcoindevkit/bdk/issues/678)
- [x]  wszdexdrf: Change configs for source-base code coverage [#708](https://github.com/bitcoindevkit/bdk/issues/708)
- [x] rajarshimaitra: Refactor testing logic from macros to pure functions[#624](https://github.com/bitcoindevkit/bdk/issues/624)

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] rajarshimaitra: Satoshi's Calculator. [#102](https://github.com/bitcoindevkit/bdk-cli/pull/102)
- [x] rajarshimaitra: Update crate documentation [#104](https://github.com/bitcoindevkit/bdk-cli/pull/104)

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] rajarshimaitra:  [Refactor] Move tutorials from Blog to Tutorial section [#103](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/103)
- [x] vladimirfomene: Update installation and interface guide of CLI [#109](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/109)
-  [x] danielabrozzoni: Update playground CSS [#112](https://github.com/bitcoindevkit/bdk/issues/624)
  
<br>

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9

**Comment by danielabrozzoni** [comment]
Can I also have https://github.com/bitcoindevkit/bitcoindevkit.org/pull/112 in the documentation PRs?

Sorry if I'm late 😭
