### ISSUE TITLE
 2022-05-10 @ 20:00, BDK Library Team Call, W20

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#2]
# BDK Library Dev Call, W20
:calendar: May 10, 2022 20:00 UTC
:round_pushpin: Discord General Voice Channel
<br/>

## Discussion Items

- [x] :calendar: New team [meeting time](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20220510&p1=157&p2=137&p3=240&p4=553)
    - 13:00 UTC for future meetings
- [x] Discord Nitro/Boosts (screensharing quality and frame rates)
- [x] Summer of Bitcoin :sun_with_face:, join discord `mentor-space`
- [x] [Taproot PR Review Club](https://discord.com/events/753336465005608961/972056837740453948):carrot: + [bdk-practice](https://github.com/afilini/bdk-practice)
    - tomorrow, 14:00 UTC Wed May 11 
- [x] BDK feature freeze tomorrow?
  - delay until TR PR ready
- [x] Any review begs? :pray:
- [x] Blockers? 🪨
- [x] May 21, [Prague Pizza Day](https://www.pizzaday.cz/), Alekos TR Talk
- [x] June 18, [Pleb.fi LA](https://bitdevsla.org/pleb-fi-1/) "taproot" themed hackathon
<br/>

## New Projects and Support 

- [x] Galoy, Test watch-only LND wallet and signing PSBT [#87](https://github.com/bitcoindevkit/bdk-cli/issues/87) 
<br/>

## Top BDK PRs and issues

- [x]  🎯 [BDK Roadmap]
- [x] :bug: SqliteDatabase set_utxo always inserts new utxo [#591](https://github.com/bitcoindevkit/bdk/issues/591)
- [x] Add support for Taproot and `tr()` descriptors [#593](https://github.com/bitcoindevkit/bdk/pull/593) :carrot: 
- [x] :construction: Merge lower priority PRs or push to 0.20.0?
- [x] `bdk_core` architecture blog post [#100](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/100) :house_with_garden: 
<br/>

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] Add key-value-db and sqlite-db features, separate wallet directories [#71](https://github.com/bitcoindevkit/bdk-cli/pull/71)
- [x] :construction: Merge lower priority PRs or push to 0.6.0?
<br/>

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
