### ISSUE TITLE
W36 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#20]
:calendar: Tues August 30, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel 

## Discussion Items

- [x] [Release 0.22.0 Feature Freeze](https://github.com/bitcoindevkit/bdk/milestone/20) ❄️ 
- [x] Assign downstream release update managers:
    - [x] `bdk-cli` : raj
    - [x] `bdk-reserves`: notmandatory
    - [x] `wasm playground` : danielabrozzoni   
    - [x] `bdk-ffi` : thunderbiscuit
- [ ] bdk_core + fedimint Kuala Lumpur recap
- [x] Nakamoto CBF Integration
- [x] https://github.com/weareseba/bdk-reserves/issues/9
- [x] [Synchronized Bitcoin/LN Wallet Storage Provider (WSP)](https://docs.google.com/document/d/1DfV7m2fBAjehZLMe_g9eACUkKFuNF2er7Q6tK8bkrv8/comment)
- [x] [TAB Conf 2022](https://2022.tabconf.com/), Atlanta, GA, Oct 12-15
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] what's new?

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x]  [notmandatory](https://github.com/notmandatory): Update DEVELOPMENT_CYCLE.md to work with [patch.crates-io] [#544](https://github.com/bitcoindevkit/bdk/pull/544)
- [x] [josediegorobles](https://github.com/josediegorobles): Problem at use bdk 0.19 with wasm [#646](https://github.com/bitcoindevkit/bdk/issues/646)
- [x]  [wszdexdrf](https://github.com/wszdexdrf): Add a custom signer for hardware wallets [#682](https://github.com/bitcoindevkit/bdk/pull/682) 
- [x] [csralvall](https://github.com/csralvall):  Add get_selection function [#727](https://github.com/bitcoindevkit/bdk/pull/727)
- [ ]  [evanlinjin](https://github.com/evanlinjin): Multi descriptor: Introduce DatabaseFactory trait [#654](https://github.com/bitcoindevkit/bdk/pull/654)
- [x]  [notmandatory](https://github.com/notmandatory): Add fee_amount() and fee_rate() functions to PsbtUtils trait [#728](https://github.com/bitcoindevkit/bdk/pull/728) 🙏 

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] [rajarshimaitra](https://github.com/rajarshimaitra): Satoshi's Calculator. [#102](https://github.com/bitcoindevkit/bdk-cli/pull/102)
- [x] [rajarshimaitra](https://github.com/rajarshimaitra): Update crate documentation [#104](https://github.com/bitcoindevkit/bdk-cli/pull/104)

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] [wszdexdrf](https://github.com/wszdexdrf): Add "Getting started with rust-hwi" blog [#113](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/113)
- [x] [csralvall](https://github.com/csralvall): Add article about changes in coin selection module [#114](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/114)
<br>

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9

**Comment by danielabrozzoni** [comment]
The link for https://github.com/bitcoindevkit/bdk/pull/556 is wrong (links to https://github.com/bitcoindevkit/bdk/pull/727 instead)

Also, can you please add https://github.com/bitcoindevkit/bdk/pull/682? Thanks! :)
