### ISSUE TITLE
W38 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#22]
:calendar: Tues September 13, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel 

## Discussion Items

- [x] [Release 0.22.0](https://github.com/bitcoindevkit/bdk/releases/tag/v0.22.0) 🎉  is published
- [x] [Release 0.23.0 Feature Freeze](https://github.com/bitcoindevkit/bdk/milestone/21) is September 28th
- [x] New PR template requires changelog info + no more CHANGELOG.md changes
- [x] bdk_core + fedimint Kuala Lumpur recap
- [x] [BTC 2022 Azores Unconference](https://btcazores.com/), Azores, Portugal, Sept 23-24
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] Unchained Capital [Caravan](https://github.com/unchained-capital/caravan), needs WASM support
- [x] [RGB Lib](https://github.com/RGB-Tools/rgb-lib) 

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x]  [josediegorobles](https://github.com/josediegorobles): Problem at use bdk 0.19 with wasm [#646](https://github.com/bitcoindevkit/bdk/issues/646)
- [x]  [bucko13](https://github.com/bucko13): add extended descriptor multisig metadata to policy extraction [#626](https://github.com/bitcoindevkit/bdk/pull/626)
- [x]  [benthecarman](https://github.com/benthecarman): Make EsploraBlockchain accessable to outside libraries [#568](https://github.com/bitcoindevkit/bdk/issues/568)
- [x]  [notmandatory](https://github.com/notmandatory): Add fee_amount() and fee_rate() functions to PsbtUtils trait [#728](https://github.com/bitcoindevkit/bdk/pull/728)
- [x] [csralvall](https://github.com/csralvall): Add get_selection function [#727](https://github.com/bitcoindevkit/bdk/pull/727)
- [x]  [vladimirfomene](https://github.com/vladimirfomene): Add API to delete spent UTXOs from database [#725](https://github.com/bitcoindevkit/bdk/pull/725)
- [x]  [evanlinjin](https://github.com/evanlinjin): Make RpcBlockchain import more efficient [#740](https://github.com/bitcoindevkit/bdk/pull/740)
- [x]  [rajarshimaitra](https://github.com/rajarshimaitra): Refactor testing logic from macros to pure functions [#624](https://github.com/bitcoindevkit/bdk/pull/624)

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x]  TBD:  AUDIT failure due to bdk + cbf dependency `rocksdb` [#119](https://github.com/bitcoindevkit/bdk-cli/pull/119)
- [x]  [rajarshimaitra](https://github.com/rajarshimaitra): Update crate documentation [#104](https://github.com/bitcoindevkit/bdk-cli/pull/104) 
- [x]  [danielabrozzoni](https://github.com/danielabrozzoni): Create wallet dir only when necessary [#116](https://github.com/bitcoindevkit/bdk-cli/pull/116)

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x]  [danielabrozzoni](https://github.com/danielabrozzoni): Update the playground to the latest bdk-cli [#118](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/118)
- [x]  [csralvall](https://github.com/csralvall): Add article about changes in coin selection module [#114](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/114)
- [x]  [BitcoinZavior](https://github.com/BitcoinZavior): Exploring BDK with BDK-RN [#115](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/115)
<br>

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
