### ISSUE TITLE
W39 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#24]
# W39, BDK Library Dev Call
:calendar: Tues September 27, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] ISO weeks #26 😵‍💫 
- [x] `bdk` code freeze this Wed. Sept. 28 ❄️
  - [x] Tester for `bdk-cli`, Steve
  - [x] Tester for `bdk-ffi`, Steve
  - [x] Tester for `bdk-kotlin`, Thunderbiscuit
  - [x] Tester for `bdk-swift`, Steve
  - [x] Tester for `bdk-python`, Thunderbiscuit
  - [x] Tester for `bdk wasm`, Daniela
- [x] `bdk-cli` release 0.6.0, today?
- [x] [BTC 2022 Azores Unconference](https://btcazores.com/) + bdk_core update
- [x] [TABconf](https://tabconf.com/), Atlanta, Oct. 12-15
- [x] [Legends of Lightning](https://makers.bolt.fun/tournaments/1/overview), Online, Oct. 11 - Dec. 7
- [x] Any review begs? :pray:
   - [x]  [thunderbiscuit](https://github.com/thunderbiscuit): Make add_recipient() take any ScriptPubKey [(bdk-ffi) #192](https://github.com/bitcoindevkit/bdk-ffi/pull/192)
- [x] Blockers? 🪨

## New Projects and Support

- [x] Block team: electrum and esplora clients don't update `Progress` callback
- [x] Block team:  multi-threading issues on mobile, TBD

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] [afilini](https://github.com/afilini): Make EsploraBlockchain accessable to outside libraries [#568](https://github.com/bitcoindevkit/bdk/issues/568)
- [x] [vladimirfomene](https://github.com/vladimirfomene): Add API to delete spent UTXOs from database [#725](https://github.com/bitcoindevkit/bdk/pull/725)
- [x]  [evanlinjin](https://github.com/evanlinjin): Make RpcBlockchain import more efficient [#740](https://github.com/bitcoindevkit/bdk/pull/740) 
   - [x] Removed from 0.23.0 release
- [x]  [evanlinjin](https://github.com/evanlinjin): Add vscode filter to gitignore [#762](https://github.com/bitcoindevkit/bdk/pull/762)
   - [x] Will add for vscode since it's popular, but also check out global .gitignore  

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] [thunderbiscuit](https://github.com/thunderbiscuit): High level write-up of what you can do with bdk-ffi [#88](https://github.com/bitcoindevkit/bitcoindevkit.org/issues/88)
- [x]  [csralvall](https://github.com/csralvall): Add article about changes in coin selection module [#114](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/114)
- [x]  [BitcoinZavior](https://github.com/BitcoinZavior): Exploring BDK with BDK-RN [#115](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/115)
   - [x] has a few final updates, and then this is ready. Also working on bdk-flutter blog post.

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9

**Comment by ConorOkus** [comment]
Review beg - https://github.com/bitcoindevkit/bdk-ffi/pull/192

**Comment by ConorOkus** [comment]
Would be good to discuss projects for the bolt.fun tournament - https://makers.bolt.fun/tournaments/1/overview

**Comment by evanlinjin** [comment]
https://github.com/bitcoindevkit/bdk/pull/762
