### ISSUE TITLE
W41 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#27]
:calendar: Tues October 11, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] `bdk` [0.23.0 Release](https://github.com/bitcoindevkit/bdk/releases/tag/v0.23.0) 🎉 
- [x] `bdk-cli` [0.6.0 Release](https://github.com/bitcoindevkit/bdk-cli/releases/tag/v0.6.0) 🎉 
- [x] ["The Road to BDK 1.0"](https://bitcoindevkit.org/blog/road-to-bdk-1/)
- [x] [BDK Core project board](https://github.com/users/LLFourn/projects/2/views/1)
- [x] Website SEO ?
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] first new project or support issue

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x]  [wszdexdrf](https://github.com/wszdexdrf): timestamp timelocks are not satisfied [#642](https://github.com/bitcoindevkit/bdk/issues/642)
- [x]  [rajarshimaitra](https://github.com/rajarshimaitra): nakamoto as Compact Block Filter Blockchain [#751](https://github.com/bitcoindevkit/bdk/pull/751)
- [x] [csralvall](https://github.com/csralvall): Add process_and_select_coins function [#727](https://github.com/bitcoindevkit/bdk/pull/727)
- [x]  [rajarshimaitra](https://github.com/rajarshimaitra): Refactor testing logic from macros to pure functions [#624](https://github.com/bitcoindevkit/bdk/pull/624) 
- [x]  [wszdexdrf](https://github.com/wszdexdrf): Add get_block_headers and check timestamps [#669](https://github.com/bitcoindevkit/bdk/pull/624) 
- [x]  [danielabrozzoni](https://github.com/danielabrozzoni): Add HWI example in docs [#758](https://github.com/bitcoindevkit/bdk/pull/758) 
- [x]  [evanlinjin](https://github.com/evanlinjin): Deprecate list_unspent which has an unnecessary .collect() [#766](https://github.com/bitcoindevkit/bdk/pull/766)
- [x]  [evanlinjin](https://github.com/evanlinjin): Fix how descriptor checksums are calculated [#765](https://github.com/bitcoindevkit/bdk/pull/765)
- [x]  [evanlinjin](https://github.com/evanlinjin): FeeRate calculation fixes [#774](https://github.com/bitcoindevkit/bdk/pull/774) 
 
## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] [rajarshimaitra](https://github.com/rajarshimaitra): Update bdk version to 0.23.0 [#123](https://github.com/bitcoindevkit/bdk-cli/pull/123)
- [x]  [rajarshimaitra](https://github.com/rajarshimaitra): Migrate from structopt to clap. [#124](https://github.com/bitcoindevkit/bdk-cli/pull/124)
- [x]  [rajarshimaitra](https://github.com/rajarshimaitra): Remove cbf [#125](https://github.com/bitcoindevkit/bdk-cli/pull/125)

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] [waterst0ne](https://github.com/waterst0ne): Add bdk bdk-cli appendix to "Mastering Bitcoin" 2nd Edition [#87](https://github.com/bitcoindevkit/bitcoindevkit.org/issues/87)
- [x] [ConorOkus](https://github.com/ConorOkus): Add example projects [#119](https://github.com/bitcoindevkit/bitcoindevkit.org/issues/119)
- [x] [thunderbiscuit](https://github.com/thunderbiscuit): High level write-up of what you can do with bdk-ffi [#88](https://github.com/bitcoindevkit/bitcoindevkit.org/issues/88)

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9

**Comment by evanlinjin** [comment]
@notmandatory could we add https://github.com/bitcoindevkit/bdk/pull/774 to the call as well? Although it is still a draft, it is rather important imo.
