### ISSUE TITLE
W45 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#30]
:calendar: Tues October 25, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] [BDK Core project board](https://github.com/users/LLFourn/projects/2/views/1)
   - coin selection
   - miniscript planning
   - chain sync
- [x] New release of `rust-esplora-client` with `rust-bitcoin` [0.29 support]
- [x] `bdk` `rust-bitcoin` [0.29 support for `rust-miniscript`]
- [x] [Bitcoin4India conference](https://www.conference.bitcoin4india.org/) Panjim, Nov 5-6
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

[0.29 support]: https://github.com/bitcoindevkit/rust-esplora-client/pull/20
[0.29 support for `rust-miniscript`]: https://github.com/rust-bitcoin/rust-miniscript/milestone/1?closed=1

## New Projects and Support

- [x] @futurepaul, Mutiny, currently LDK send only, could use BDK for on-chain

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x]  [afilini](https://github.com/afilini): bitcoindevkit/bdk#770
- [x] [evanlinjin](https://github.com/evanlinjin): bitcoindevkit/bdk#765

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] [rajarshimaitra](https://github.com/rajarshimaitra): bitcoindevkit/bdk-cli#123
- [x] [rajarshimaitra](https://github.com/rajarshimaitra): bitcoindevkit/bdk-cli#124 

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] [BitcoinZavior](https://github.com/BitcoinZavior): bitcoindevkit/bitcoindevkit.org#123

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9

**Comment by tnull** [comment]
Would be great to talk about a timeline for the next Esplora client release. In particular, LDK Lite would make use of a recently merged PR. It would therefore would be nice if the upcoming BDK release (that will hopefully also finally include an upgrade of `rust-bitcoin`), would include the updated Esplora client already.

**Comment by notmandatory** [comment]
The hold-up right now for upgrading BDK to `rust-bitcoin` 0.29 is that we also need the `rust-miniscript` crate updated, and I haven't seen an ETA yet on that (https://github.com/rust-bitcoin/rust-miniscript/milestone/1?closed=1).  But we should still be able to do a release of the Esplora client. I'll add it to the agenda to discuss on Tuesday. And maybe we can also add a feature flag or something like that to use `rust-bitcoin` 0.29 instead of 0.28 in the esplora client.

**Comment by notmandatory** [comment]
For `bdk` we'll keep making dependency updates and bug fixes on the same monthly schedule, but we just not doing any big feature changes until the `bdk_core` PRs are merged. So as soon as `rust-miniscript` is updated we can upgrade the `rust-bitcoin` version too.

**Comment by tnull** [comment]
> For `bdk` we'll keep making dependency updates and bug fixes on the same monthly schedule, but we just not doing any big feature changes until the `bdk_core` PRs are merged. So as soon as `rust-miniscript` is updated we can upgrade the `rust-bitcoin` version too.

Ah, that's good news!

**Comment by notmandatory** [comment]
Yes, and if necessary we can keep back-porting fixes to what ever the final pre-1.0 version is to give users time to update to 1.0.

**Comment by tnull** [comment]
`rust-miniscript` had a release just a few hours ago 🎉

**Comment by notmandatory** [comment]
I fixed the week # on this.. I had 45, but should be week 43.
