### ISSUE TITLE
W45 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#31]
:calendar: Tues November 8, 2022 ~~13:00 UTC~~ 14:00 UTC (Sorry daylight savings messed up Discord event time)
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] [`bdk` 0.24.0 release](https://github.com/bitcoindevkit/bdk/releases/tag/v0.24.0) 🎉 
- [x] Potential DoS bug and dealing with CVEs type issues
- [x] [BDK Core Project] update
- [x] [Lightning Halloween](https://bolt.fun/hackathons/lightning-halloween/) Viareggio, Recap
- [ ] [Bitcoin for India Conference](https://www.conference.bitcoin4india.org/) Panjim, Recap
- [x] [Dakar Bitcoin Days Hackathon](https://www.dakarbitcoindays.com/hackathon) Dec 2-3 in Dakar, Sénégal
- [x] Team co-working week of Dec 4th in Thailand
- [x] Team co-working week of Feb 5th in Nashville, TN at Bitcoin Park 
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] Block: bitcoindevkit/bdk#794
- [x] Mutiny: bitcoindevkit/bdk#789

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] bitcoindevkit/bdk#793
- [x] bitcoindevkit/bdk#785
- [x] bitcoindevkit/bdk#774
- [ ] bitcoindevkit/rust-electrum-client#75
- [x] rust-bitcoin/rust-bitcoincore-rpc#230
- [x] bitcoindevkit/bdk#795

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] bitcoindevkit/bdk-cli#129

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] bitcoindevkit/bitcoindevkit.org#128
- [x] bitcoindevkit/bitcoindevkit.org#114

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by 0xarvin** [comment]
Not sure if this is the right place to walk about it but would love to chat about this:

https://github.com/bitcoindevkit/rust-electrum-client/issues/75

**Comment by notmandatory** [comment]
Hi, sure I'll add https://github.com/bitcoindevkit/rust-electrum-client/issues/75 to the list to discuss.
