### ISSUE TITLE
W47 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#33]
:calendar: Tues November 22, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] [`bdk` 0.25.0 feature freeze](https://github.com/bitcoindevkit/bdk/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Release+0.25.0+Feature+Freeze%22) 🎉 
- [x] [BDK Core Project] update
- [x] How to deal with/fix the clippy warnings/errors introduced with rust 1.65 (see Add get_merkle_block API call rust-esplora-client#28 (comment))
- [x] How LDK, BDK and generally the larger rust-bitcoin ecosystem can ensure faster turnaround times for integrating upstream releases (i.e., start a discussion what our strategy could be towards that end)
- [x] [Bitcoin for India Conference](https://www.conference.bitcoin4india.org/) Panjim, Recap
- [x] [Dakar Bitcoin Days Hackathon](https://www.dakarbitcoindays.com/hackathon) Dec 2-3 in Dakar, Sénégal
- [x] Team co-working week of Dec 4th in Thailand
- [x] Team co-working week of Feb 5th in Nashville, TN at Bitcoin Park 
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] LDK: bitcoindevkit/bdk#709

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] @LLFourn bitcoindevkit/bdk#785
- [x] @vladimirfomene bitcoindevkit/bdk#746
- [x] @raj bitcoindevkit/bdk#624

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] @rajarshimaitra bitcoindevkit/bdk-cli#124

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] bitcoindevkit/bitcoindevkit.org#123

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by tnull** [comment]
I have two things for the agenda:

- How to deal with/fix the clippy warnings/errors introduced with rust 1.65 (see https://github.com/bitcoindevkit/rust-esplora-client/pull/28#issuecomment-1303216833)
- How LDK, BDK and generally the larger `rust-bitcoin` ecosystem can ensure faster turnaround times for integrating upstream releases (i.e., start a discussion what our strategy could be towards that end)
