### ISSUE TITLE
W48 BDK Language Bindings Dev Call

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/.github#34]
See the proposed agenda here: https://hackmd.io/@thunderbiscuit/devcalls/.

The call is scheduled for Tuesday, November 29 2022 at 13:00 UTC.

Comment on this issue if you'd like us to add anything to the agenda!

**Comment by thunderbiscuit** [comment]
# Bitcoindevkit Language Bindings Dev Call
:calendar: _November 29, 2022 13:00 UTC_
:round_pushpin: _Discord General Voice Channel_

## Discussion Items
- [x] New bdk-ffi structure :tada:
- [x] Sunsetting the individual languages' project boards
- [x] Libraries providing syntactic sugar, helpers, wrappers, defaults on top of the bindings API ([#265](https://github.com/bitcoindevkit/bdk-ffi/issues/265))
- [x] Flutter API
- [x] 1.0 release
- [x] [uniffi-bindings-template](https://github.com/thunderbiscuit/uniffi-bindings-template)
- [x] [Rename repository to something more intuitive](https://github.com/bitcoindevkit/bdk-ffi/issues/232)
- [x] `jna.Pointer` exception [#258](https://github.com/bitcoindevkit/bdk-ffi/issues/258)
- [x] Publishing our first snapshot version (`0.12.0-SNAPSHOT`) of bdk-android
- [x] Any review begs? :pray:
- [x] Blockers? 🪨
- [x] [Project board](https://github.com/orgs/bitcoindevkit/projects/8) :clipboard:
<br/>

## Dependent Projects and Support
<br/>

## Top Issues and PRs
**Open PR:** [Add from_string() methods to `DescriptorPrivateKey` and `DescriptorPublicKey`](https://github.com/bitcoindevkit/bdk-ffi/pull/247)
**Open PR:** [Add descriptor templates](https://github.com/bitcoindevkit/bdk-ffi/pull/260)
**Merged PR:** [Add bdk-swift](https://github.com/bitcoindevkit/bdk-ffi/pull/259)
**Open Issue:** [Add custom signer](https://github.com/bitcoindevkit/bdk-ffi/issues/222)
**Open Issue:** [Explore KMP as viable library ](https://github.com/bitcoindevkit/bdk-ffi/issues/249)
