### ISSUE TITLE
W1 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#37]
:calendar: Tues January 3, 2023 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] bitcoindevkit/bdk#827
- [x] [BDK Core Project] update
- [x] Team co-working week of Dec 4th in Thailand Recap
- [x] Team co-working week of Feb 5th in Nashville, TN at Bitcoin Park
- [x] BDK Workshop [Feb 11 in Nashville, TN at Bitcoin Park](https://www.meetup.com/bitcoinpark/events/290296920/)
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] TBD

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] bitcoindevkit/bdk#813
- [x] bitcoindevkit/bdk#561

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] bitcoindevkit/bdk-cli#128

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x]  bitcoindevkit/bitcoindevkit.org#123
- [x] bitcoindevkit/bitcoindevkit.org#134

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by notmandatory** [comment]
TODOs:
- [ ] bitcoindevkit/bdk#813 see if thiserror can be made an optional dependency
- [ ] bitcoindevkit/bdk#561 ask to add maintainer and fork if needed
- [ ] bdk-cli skip release 0.25 and merge open PRs for 0.26 release
- [ ] @notmandatory open issue with details of problem with libtor on mac M1
