### ISSUE TITLE
W3 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#39]
:calendar: Tues January 17, 2023 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] [BDK Core Project] update
- [x] [bdk-cli 0.26 release](https://github.com/bitcoindevkit/bdk-cli/releases/tag/v0.26.0) 🎉 
- [x] Team co-working week of Feb 5th in Nashville, TN at Bitcoin Park
- [x] BDK Workshop [Feb 11 in Nashville, TN at Bitcoin Park](https://www.meetup.com/bitcoinpark/events/290296920/)
- [x] Anyone going to [BTC Prague](https://www.btcprague.com/) June 8-10?
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [ ] TBD

## Top BDK Core Staging PRs and issues

- [x] 🎯 [BDK Core Staging Roadmap]
- [x] LLFourn/bdk_core_staging#150

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] bitcoindevkit/bdk#791
- [x] bitcoindevkit/bdk#814
- [x] bitcoindevkit/bdk#815
- [x] bitcoindevkit/bdk#816
- [x] bitcoindevkit/bdk#823
- [x] bitcoindevkit/bdk#831

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] bitcoindevkit/bdk-cli#135

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x]  bitcoindevkit/bitcoindevkit.org#123
- [x] bitcoindevkit/bitcoindevkit.org#134
- [x] bitcoindevkit/bitcoindevkit.org#135
- [x] bitcoindevkit/bitcoindevkit.org#136

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
