### ISSUE TITLE
2022-05-17 @ 14:00 UTC, BDK Language Bindings Team Call, W21

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoindevkit/.github#4]
# Bitcoindevkit Language Bindings Dev Call
:calendar: _May 17, 2022 14:00 UTC_
:round_pushpin: _Discord General Voice Channel_
<br/>

## Discussion Items
- [x] bdk-ffi `0.6.0` released! 🎉
- [x] bdk-kotlin `0.6.0` released 🎉
- [x] bdk-swift `0.3.0` released 🎉
- [x] BDK/LDK iOS wallet @danielnordh
- [x] Support for `x86` on bdk-android
- [x] How can we help the React Native library?
- [x] "Live docs/office hours" idea
- [x] Can we clean up and keep alive the iOS version of Devkit Wallet? Should we try and bring it as an official example?
- [x] Any review begs? :pray:
- [x] Blockers? 🪨
<br/>

## Dependent Projects and Support
- [Lava Wallet](https://oasis-lentil-525.notion.site/Lava-Whitepaper-5ed6b50ca8ef4260a073db8ef6978708) [@MarediaShehzan](https://twitter.com/MarediaShehzan) and [@lava_xyz](https://twitter.com/lava_xyz)
- DailyWallet ([GitHub](https://github.com/bdgwallet/dailywallet))
<br/>

## Top Issues and PRs
- [x] Add child key pair generation api ([bdk-ffi #154](https://github.com/bitcoindevkit/bdk-ffi/pull/154))
- [x] Update library to new bdk-ffi API version 0.6.0 ([bdk-python #18](https://github.com/bitcoindevkit/bdk-python/pull/18))
- [x] BDKSwiftExample [PR #5](https://github.com/futurepaul/BdkSwiftSample/pull/5)
- [x] Add address index to return type of `get_address` ([bdk-ffi #137](https://github.com/bitcoindevkit/bdk-ffi/pull/137))
- [x] Add OP_RETURN ([bdk-ffi issue #132](https://github.com/bitcoindevkit/bdk-ffi/issues/132))
- [x] Add functions to get current block height and hash ([bdk-ffi issue #151](https://github.com/bitcoindevkit/bdk-ffi/issues/151))
<br/>

## Boards
[FFI project board](https://github.com/orgs/bitcoindevkit/projects/8)
[Kotlin project board](https://github.com/orgs/bitcoindevkit/projects/10/views/1)
[Swift project board](https://github.com/orgs/bitcoindevkit/projects/11)
[Python project board](https://github.com/orgs/bitcoindevkit/projects/12)
