### ISSUE TITLE
W5 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#42]
:calendar: Tues January 31, 2023 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] [Release 0.27.0 Feature Freeze](https://github.com/bitcoindevkit/bdk/milestone/25)
- [x] [BDK Core Project] update
- [x] Team co-working week of Feb 5th in Nashville, TN at Bitcoin Park
- [x] BDK Workshop [Feb 11 in Nashville, TN at Bitcoin Park](https://www.meetup.com/bitcoinpark/events/290296920/)
- [x] Anyone going to [BTC Prague](https://www.btcprague.com/) June 8-10?
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] [Bull Bitcoin](https://www.bullbitcoin.com/)
- [x] [Anchor Watch](https://www.anchorwatch.com/)

## Top BDK Core Staging PRs and issues

- [x] 🎯 [BDK Core Staging Roadmap]
- [x] Blockchain Testing

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] bitcoindevkit/bdk#840
- [x] bitcoindevkit/bdk#841
- [x] bitcoindevkit/bdk#845
- [x] bitcoindevkit/bdk#846

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] bitcoindevkit/bdk-cli#135
- [x] bitcoindevkit/bdk-cli#140

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] bitcoindevkit/bitcoindevkit.org#134
- [x] bitcoindevkit/bitcoindevkit.org#135
- [x] bitcoindevkit/bitcoindevkit.org#136

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
