### ISSUE TITLE
W7 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#43]
:calendar: Tues February 14, 2023 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] [Release 0.27.0](https://github.com/bitcoindevkit/bdk/releases/tag/v0.27.0) 🎉 
- [x] Freeze bdk `master` branch in prep for `bdk_core` PRs?
- [x] [Bitcoin 2023 Miami](https://b.tc/conference/) May 18-20
- [x] [BTC Prague](https://www.btcprague.com/) June 8-10
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] [node-bdk](https://github.com/mcroad/node-bdk)

## Top [BDK Core Staging](https://github.com/LLFourn/bdk_core_staging) PRs and issues

- [x] 🎯 [BDK Core Staging Roadmap]
- [x] Blockchain Testing

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] bitcoindevkit/bdk#816
- [x] bitcoindevkit/bdk#839
- [x] bitcoindevkit/bdk#840
- [x] bitcoindevkit/bdk#850
- [x] bitcoindevkit/bdk#857
- [x] bitcoindevkit/bdk#862
- [x] bitcoindevkit/rust-electrum-client#94

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] bitcoindevkit/bdk-cli#143
- [x] bitcoindevkit/bdk-cli#135

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] bitcoindevkit/bitcoindevkit.org#135
- [x] bitcoindevkit/bitcoindevkit.org#136
- [x] bitcoindevkit/bitcoindevkit.org#139

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
