### ISSUE TITLE
W11 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#48]
:calendar: Tues March 14, 2023 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] BDK 0.27.2 Release
- [x] BDK 1.0.0-alpha.0 Release
- [x] Spiral Q1 2023 Newsletter
- [x] [Bitcoin 2023 Miami](https://b.tc/conference/) May 18-20
- [x] [BTC Prague](https://www.btcprague.com/) June 8-10
- [x] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [x] [Book of BDK](https://github.com/thunderbiscuit/book-of-bdk)
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] [Summer of Bitcoin](https://www.summerofbitcoin.org/project-ideas-details/bdk/r/rec6cqlRFzXRt6b6z)
- [x] [10101](https://github.com/get10101/10101/)

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] bitcoindevkit/bdk#793
- [x] bitcoindevkit/bdk#888
- [x] bitcoindevkit/bdk#884
- [x] bitcoindevkit/bdk#823
- [x] bitcoindevkit/rust-esplora-client#37

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] bitcoindevkit/bdk-cli#148
- [x] bitcoindevkit/bdk-cli#149

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] TBD

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
