### ISSUE TITLE
W13 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#50]
:calendar: Tues March 28, 2023 13:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] Q2 Spiral Update
- [x] [Bitcoin 2023 Miami](https://b.tc/conference/) May 18-20
- [x] [BTC Prague](https://www.btcprague.com/) June 8-10
- [x] [Candadian Bitcoin Conf](https://canadianbitcoinconf.com/) June 17-18
- [x] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [x] [BTC Azores](https://btcazores.com/) Sept 23-24
- [x] [Book of BDK](https://github.com/thunderbiscuit/book-of-bdk)
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] TBD

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] bitcoindevkit/rust-esplora-client#44
- [x] bitcoindevkit/bdk#897
- [x] bitcoindevkit/bdk#914
- [x]  bitcoindevkit/bdk#894
- [x] bitcoindevkit/bdk#895
- [x] bitcoindevkit/bdk#486

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] bitcoindevkit/bdk-cli#148
- [x] bitcoindevkit/bdk-cli#149

## Top Documentation PRs and issues

- [x] 🎯 [Documentation Roadmap]
- [x] TBD

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
