### ISSUE TITLE
W19 BDK Lib Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#57]
:calendar: Tues May 9, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [x] New BDK [Maintenance](https://github.com/orgs/bitcoindevkit/projects/6) and [1.0](https://github.com/orgs/bitcoindevkit/projects/14) Project Boards
- [x] HackMD?
- [x] Good first issues
- [x] Summer of Bitcoin
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## Upcoming Events

- [x] [Bitcoin 2023 Miami](https://b.tc/conference/) May 18-20
- [x] [BTC Prague](https://www.btcprague.com/) June 8-10
- [x] [Candadian Bitcoin Conf](https://canadianbitcoinconf.com/) June 17-18
- [x] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [x] [BTC Azores](https://btcazores.com/) Sept 23-24

## New Projects and Support

- [x] Galoy batching

## Top BDK 1.0 PRs and issues

- [x] 🎯 [BDK 1.0] Next Release
- [x] bitcoindevkit/bdk#971
- [x] bitcoindevkit/bdk#965
- [x] bitcoindevkit/bdk#899
- [x] bitcoindevkit/bdk#966

## Top BDK_CLI PRs and issues

- [ ] 🎯 [BDK-CLI Roadmap]
- [ ] bitcoindevkit/bdk-cli#153
- [ ] bitcoindevkit/bdk-reserves#26

## Top Other PRs and issues

- [ ] bitcoindevkit/rust-esplora-client#45

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]:https://github.com/orgs/bitcoindevkit/projects/6/views/4
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by notmandatory** [comment]
* HackMD good for live note taking and collaborative discussions, should be migrated to github for future findability.  @thunderbiscuit created an free org account to play with, don't need private docs.  
* Galoy, chain sync + Fulcrum (electrum), notification for unconfirmed tx changes, ie dropped
* Galoy, how to tell txbuilder to use a UTXO and add others as needed, look at manually_selected_only = false
* For TxBuilder and multi-descriptor wallet work, current focus will be on reviewing alpha.1 PRs. In parallel @danielabrozzoni will take the lead on a design proposal for TxBuilder changes and @rajarshimaitra for multidescriptor wallet changes, with team providing design review and feedback. After everyone had time to understand proposed changes we can discuss order for getting PRs in.

**Comment by thunderbiscuit** [comment]
The HackMD team page is [here](https://hackmd.io/team/bdk).
