### ISSUE TITLE
W21 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#59]
:calendar: Tues May 23, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel   

## Discussion Items

- [ ] Summer of Bitcoin
- [ ] Any review begs? :pray:
- [ ] Blockers? 🪨

## Upcoming Events

- [ ] [BTC Prague](https://www.btcprague.com/) June 8-10
- [ ] [Candadian Bitcoin Conf](https://canadianbitcoinconf.com/) June 17-18
- [ ] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [ ] [BTC Azores](https://btcazores.com/) Sept 23-24

## New Projects and Support

- [ ] TBD

## Top BDK 1.0 PRs and issues

- [ ] 🎯 [BDK 1.0] Next Release
- [ ] bitcoindevkit/bdk#971
- [ ] bitcoindevkit/bdk#976
- [ ] bitcoindevkit/bdk#965
- [ ] bitcoindevkit/bdk#899
- [ ] bitcoindevkit/bdk#966
- [ ] bitcoindevkit/bdk#987

## Top BDK_CLI PRs and issues

- [ ] 🎯 [BDK-CLI Roadmap]
- [ ] bitcoindevkit/bdk-cli#153
- [ ] bitcoindevkit/bdk-reserves#26

## Top Other PRs and issues

- [ ] bitcoindevkit/rust-esplora-client#45

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
