### ISSUE TITLE
W23 BDK Lib Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#60]
:calendar: Tues June 6, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel

**Please add comments to this issue to suggest issues and PRs to discuss.**

## General Discussion Items

- [ ] BDK 1.0 milestones and timeline
- [ ] [rust-esplora-client v0.5.0](https://github.com/bitcoindevkit/rust-esplora-client/releases/tag/v0.5.0) released 🎉 
- [ ] Summer of Bitcoin
- [ ] Any review begs? :pray:
- [ ] Blockers? 🪨

## New Projects and Support

- [ ] [Galoy](https://galoy.io/), bitcoindevkit/bdk#985
- [ ] [Fortris](https://fortris.com/), currently using [bcoin](https://github.com/bcoin-org/bcoin)

## Top BDK 1.0 PRs and issues

- [ ] 🎯 [BDK 1.0] Next Release
- [ ] bitcoindevkit/bdk#976
- [ ] bitcoindevkit/bdk#964
- [ ] bitcoindevkit/bdk#991

## Top BDK_CLI PRs and issues

- [ ] 🎯 [BDK-CLI Roadmap]
- [ ] bitcoindevkit/bdk-cli#153
- [ ] bitcoindevkit/bdk-reserves#26

## Top Other PRs and issues

- [ ] bitcoindevkit/bitcoindevkit.org#143

## Upcoming Events

- [ ] [BTC Prague](https://www.btcprague.com/) June 8-10
- [ ] [Candadian Bitcoin Conf](https://canadianbitcoinconf.com/) June 17-18
- [ ] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [ ] [BTC Azores](https://btcazores.com/) Sept 23-24

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by evanlinjin** [comment]
I would like to talk about what I've been working on last week. Other than assisting @danielabrozzoni with the `CoinControl` stuff, I started work on a `LocalChain` that utilizes a linked list: https://github.com/bitcoindevkit/bdk/pull/1002 (this was originally @LLFourn's idea, but I see how it will simplify our API).

```rust
pub struct CheckPoint {
    pub height: u32,
    pub hash: BlockHash,
    pub prev: Option<Arc<CheckPoint>>,
}
```

Imagine two threads, one holding the `IndexedTxGraph` and one sending from the chain-data-source. To start the chain-data-src thread, we only need to send the tip `Arc<CheckPoint>`. The chain-data-src can iterate in reverse to find the "point of agreement" without having to hold a lock on any structure, or having the main thread send over 10 blocks initially.

Likewise, when the chain-data thread discovers a new block, the tip `Arc<CheckPoint>` is the only thing we need to send to the main thread. No need to think about the previous blocks to include in order for the update to connect with the original chain.

Ideally I would like to include the RPC chain example with this PR as it shows how it is used.

**Comment by evanlinjin** [comment]
The other thing I would like to discuss, is how we can come up with a good guideline for spec-writing. Unfortunately @danielabrozzoni will not be able to make the call.

I already have some thoughts on this: https://gist.github.com/evanlinjin/41e6a23cc08e888884bded327e290866?permalink_comment_id=4587231#gistcomment-4587231
