### ISSUE TITLE
W22 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#7]
# W22 BDK Library Dev Call
:calendar: May 24, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel 

## Discussion Items

- [x] `bdk` release 0.19.0 without :carrot: Taproot?
- [x] Or release SQLite UTXO fix in 0.18.1?
    - Release fixes + Taproot in 0.19.0
- [x] `bdk-cli` release 0.5.0 ready?
    - Disable sqlite-db feature then ok
- [x] News from Prague :pizza: pizza day
    - afilini ["Five taproot tricks you didn’t know about"](https://docs.google.com/presentation/d/1KDCvP8yTGpHlMWX-et_I_JuqO7Ud0wf1nr_ENaIzaWs/edit?usp=sharing)
    - danielabrozzoni "Life is short, Bitcoin is forever"
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] Ishi Stackmate, dart-ffi + flutter

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] afilini: Add support for Taproot and tr() descriptors [PR #593](https://github.com/bitcoindevkit/bdk/pull/593)
- [x] raj: The rpc blockchain doesn't work with Bitcoin Core 23.0 [Issue #598](https://github.com/bitcoindevkit/bdk/issues/598)
- [x] llfourn: Add bdk_core blog post [Docs #100](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/100)
- [x] matt: Support lighting's special feerates [Issue #608](https://github.com/bitcoindevkit/bdk/issues/608)

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
- [x] raj: Unleash the power of Bitcoin Core into bdk-cli [PR #92](https://github.com/bitcoindevkit/bdk-cli/pull/92)

<br>

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7#
