### ISSUE TITLE
W33 Lib Team Call

### ISSUE THREAD

**Issue by nondiremanuel** [bitcoindevkit/.github#72]
:calendar: Tues August 15, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel

Meeting Notes: https://hackmd.io/L4s-p7hpQPWI8QMm6rhBkA

**Please add comments to this issue to suggest issues and PRs to discuss.**

## General Discussion Items

- [x] BDK 1.0 milestones and timeline
- [x] BDK Review Club
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] bitcoindevkit/bitcoindevkit.org#147
- [x] bitcoindevkit/bdk#1061
- [x] bitcoindevkit/bdk#1062
- [x] bitcoindevkit/bdk#1049
- [x] bitcoindevkit/bdk#1051

### alpha.2
- [x] bitcoindevkit/bdk#1023 and bitcoindevkit/bdk#1034 -> merged 🎉
- [x] bitcoindevkit/bdk#1065
- [x] bitcoindevkit/bdk#1040
- [x] bitcoindevkit/bdk#1041 (linked to this: bitcoindevkit/bdk#896)
- [x] bitcoindevkit/bdk#1048
- [x] bitcoindevkit/bdk#922

### milestone TBD
- [x] bitcoindevkit/bdk#958 -> replaced by bitcoindevkit/bdk#1064
- [x] bitcoindevkit/bdk#816
- [x] bitcoindevkit/bdk#1055
- [x] bitcoindevkit/bdk#1067
- [x] bitcoindevkit/bdk#924 -> replaced by bitcoindevkit/bdk#1072
- [x] bitcoindevkit/bdk#1036

## Top Maintenance PRs and issues
 - [x] bitcoindevkit/bdk#1071

## Upcoming Events

- [x] [BalticHoneybadger Riga](https://baltichoneybadger.com/) Sept 2-3
- [x] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [x] [BTC Azores](https://btcazores.com/) Sept 23-24
- [x] [PlanB Lugano](https://planb.lugano.ch/?lang=it) Oct 20-21

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by danielabrozzoni** [comment]
Can we discuss https://github.com/bitcoindevkit/bdk/issues/1036? We haven't set a priority/milestone for it yet but I think we should

**Comment by nondiremanuel** [comment]
Sure, added to the list! Thanks for pointing them out @danielabrozzoni :)
