### ISSUE TITLE
W35 Lib Team Call

### ISSUE THREAD

**Issue by nondiremanuel** [bitcoindevkit/.github#74]
:calendar: Tues August 29, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel

Meeting Notes: https://hackmd.io/45zbrWLrSvmcdxrqjSze4Q

**Please add comments to this issue to suggest issues and PRs to discuss.**

## General Discussion Items

- [ ] BDK 1.0 milestones and timeline
- [ ] BDK Review Club
- [ ] Any review begs? :pray:
- [ ] Blockers? 🪨

## New Projects and Support

- [ ] bitcoindevkit/bdk#1089
- [ ] bitcoindevkit/bdk#1083 -> milestone TBD
- [ ] bitcoindevkit/bdk#1076
- [ ] bitcoindevkit/bdk#896 -> milestone TBD

### alpha.2
- [x] bitcoindevkit/bdk#1065 -> merged!!
- [ ] bitcoindevkit/bdk#1040
- [ ] bitcoindevkit/bdk#1041
- [ ] bitcoindevkit/bdk#1048
- [ ] bitcoindevkit/bdk#1064
- [ ] bitcoindevkit/bdk#1069
- [ ] bitcoindevkit/bdk#1070
- [ ] bitcoindevkit/bdk#1093

### alpha.3
- [ ]  bitcoindevkit/bdk#1072
- [ ] bitcoindevkit/bdk#1036
- [ ] bitcoindevkit/bdk#1086
- [ ] bitcoindevkit/bdk#1084
- [ ] bitcoindevkit/bdk#1079
- [ ] bitcoindevkit/bdk#1078
- [ ] bitcoindevkit/bdk#1042
- [ ] bitcoindevkit/bdk#1094

## Top Maintenance PRs and issues
 - [x] bitcoindevkit/bdk#1071 -> merged!!
 - [x] bitcoindevkit/bdk#1090

## Upcoming Events

- [ ] [BalticHoneybadger Riga](https://baltichoneybadger.com/) Sept 2-3
- [ ] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [ ] [BTC Azores](https://btcazores.com/) Sept 23-24
- [ ] [PlanB Lugano](https://planb.lugano.ch/?lang=it) Oct 20-21

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by notmandatory** [comment]
Meeting notes from today's call:

# W35 Meeting Minutes

## Agenda

- BDK 1.0 milestones and timeline
- BDK Review Club
- Review Begs?
- Blockers?

### New Projects and Support

- TBD

### Top BDK 1.0 PRs and issues


#### alpha.2


##### Ready to merge

- [#1064](https://github.com/bitcoindevkit/bdk/pull/1064): Better tests for transaction conflict handling
- [#958](https://github.com/bitcoindevkit/bdk/issues/958): More tests for IndexedTxGraph and TxGraph
- [#1084](https://github.com/bitcoindevkit/bdk/pull/1084): Enhance bdk chain structures
    - the RPC PR requires this one, so this is also priority

##### Still need review (in progress)

- [#1040](https://github.com/bitcoindevkit/bdk/pull/1040): RPC client refactor
- [#1041](https://github.com/bitcoindevkit/bdk/pull/1041): Add bitcoind_rpc chain source module
    - @vladimirfomene is working on an rpc wallet example and reorg confirmed transaction tests.
- [#1048](https://github.com/bitcoindevkit/bdk/pull/1048): Remove TransactionDetails from Wallet API
    - One more comment then @notmandary will merge it
- [#1065](https://github.com/bitcoindevkit/bdk/pull/1065): refactor!(chain): Unify ChangeSet nomenclature
    - already merged! yea!

##### New Issues

- [#1102](https://github.com/bitcoindevkit/bdk/issues/1102): Further improve unconfirmed tx conflict resolution
    - this is high priority per Evan
- [#1101](https://github.com/bitcoindevkit/bdk/issues/1101): Reintroduce descriptor checksum data to bdk::Wallet persistence
    -  another high priority per Evan

#### milestone TBD

- [#816](https://github.com/bitcoindevkit/bdk/pull/816): TOR+Esplora example
    - stay in beta.0 milstone
- [#1055](https://github.com/bitcoindevkit/bdk/pull/1055): Add Compact Block Filters Syncing
    - stay in 1.1.0-alpha.0 milestone
    - waiting on nakamoto work
- [#924](https://github.com/bitcoindevkit/bdk/pull/924): Introduce new bdk_coin_select implementation
    -  replaced by #1072
    -  moved to 2.0 since this is a big change and we already have alot to do for 1.0
- [#1036](https://github.com/bitcoindevkit/bdk/issues/1036): Use max_weight_to_satisfy instead of max_satisfaction_weight
    - leave in alpha.3 for now, TBD on moving it

### Top Maintenance PRs and issues

- [#1071](https://github.com/bitcoindevkit/bdk/pull/1071): Update rust bitcoin (BDK 0.28)
    - done! :tada:
    - also bumps esplora from 0.4 to 0.6
