### ISSUE TITLE
W37 Lib Team Call

### ISSUE THREAD

**Issue by nondiremanuel** [bitcoindevkit/.github#76]
:calendar: Tues September 12, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel

Meeting Notes: 

**Please add comments to this issue to suggest issues and PRs to discuss.**

## General Discussion Items

- [x] BDK 1.0 milestones and timeline
- [x] BDK Review Club: #1064 can be a good candidate
- [x] Any review begs? :pray:
- [x] Blockers? 🪨

## New Projects and Support

- [x] bitcoindevkit/bdk#1114
- [x] bitcoindevkit/bdk#1107: evan is not sure it should be an option
- [ ] bitcoindevkit/bdk#1104
- [ ] bitcoindevkit/bdk#1103
- [ ] bitcoindevkit/bdk#1096
- [ ] bitcoindevkit/bdk#1097 

#### Recently merged:
- [x] bitcoindevkit/bdk#1040
- [x] bitcoindevkit/bdk#1048
- [x] bitcoindevkit/bdk#1069
- [x] bitcoindevkit/bdk#1093
#### Ready to be merged: 
- [x] bitcoindevkit/bdk#1084: needs review on the last commit
#### Changes requested:
- [x] bitcoindevkit/bdk#1064 : needs some work on the commits and a further round of review
#### Need Review:
- [x] bitcoindevkit/bdk#1041: vlad is taking this one and adding some tests in a different PR. Needs more reviews anyway and addressing Lloyd's comments. Moved to the In Progress column for the moment
- [x] bitcoindevkit/bdk#1110
- [x] bitcoindevkit/bdk#1070
#### Changes requested:
- [x] bitcoindevkit/bdk#1028
#### Need Review:
- [x] bitcoindevkit/bdk#1086: needs some CI fixes and rebase
#### In progress:
- [x] bitcoindevkit/bdk#1079: Lloyd needs some clarification on the API. It still needs to be started
#### To Do:
- [x] bitcoindevkit/bdk#1036: In progress in #1115 but probably will need more work on it
- [ ] bitcoindevkit/bdk#1113
- [ ] bitcoindevkit/bdk#256
- [ ] bitcoindevkit/bdk#1101
- [ ] bitcoindevkit/bdk#1094
- [ ] bitcoindevkit/bdk#994
- [ ] bitcoindevkit/bdk#1042
- [x] bitcoindevkit/bdk#1078

### Milestone TBD:
- [ ] bitcoindevkit/bdk#1053
- [x] bitcoindevkit/bdk#1112: in progress in #1117 and needs some clarifications. To be confirmed wheter it's in milestone 2 or another one
- [ ] bitcoindevkit/bdk#1106
- [ ] bitcoindevkit/bdk#1099
- [ ] bitcoindevkit/bdk#969
- [ ] bitcoindevkit/bdk#1109
- [ ] bitcoindevkit/bdk#987

## Upcoming Events

- [x] [BalticHoneybadger Riga](https://baltichoneybadger.com/) Sept 2-3
- [x] [TABConf Atlanta](https://2023.tabconf.com) Sept 6-9
- [ ] [BTC Azores](https://btcazores.com/) Sept 23-24
- [ ] [PlanB Lugano](https://planb.lugano.ch/?lang=it) Oct 20-21

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
