### ISSUE TITLE
W43 Lib Team Call

### ISSUE THREAD

**Issue by nondiremanuel** [bitcoindevkit/.github#83]
:calendar: Tues October 24, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel

**Please add comments to this issue to suggest issues and PRs to discuss.**

## General Discussion Items

- [x] BDK 1.0 milestones and timeline (bitcoindevkit/bitcoindevkit.org#162: Roadmap blog post) -> high level functional roadmap description
- [x] BDK Review Club -> next Thursday about ci migration to Nix (bitcoindevkit/bdk#1165)
- [x] Any review begs? :pray:
- [x] Blockers? 🪨 -> some builds are broken for some problems with the dependencies. Working on it today

#### Need Review:
- [x] bitcoindevkit/bdk#1117: waiting to be reviewed
- [x] bitcoindevkit/bdk#1109: Lloyd is having some concerns on the solution proposed -> need some comments on the concerns
- [x] bitcoindevkit/bdk#1161: new to alpha.3 -> good candidate for nix ci as well
- [x] bitcoindevkit/bdk#1156: new to alpha.3 on ci -> it will need to be closed if we land to Nix ci
#### In progress:
- [x] bitcoindevkit/bdk#1028: rebased, needs some fixes. Does this fix bitcoindevkit/bdk#994? -> probably yes, but needs to be double checked. Question about the usage of a new crate (everyone ok with it?). Discussion will go on in the PR.
- [ ] bitcoindevkit/bdk#1178: WIP (evan)
- [ ] bitcoindevkit/bdk#1167: WIP (daniela)
- [ ] bitcoindevkit/bdk#1042: WIP (vlad)
- [ ] bitcoindevkit/bdk#1172: WIP (vlad), replaces 1106.
- [x] bitcoindevkit/bdk#1145: needs to be continued after discarding bitcoindevkit/bdk#1163 solution
- [x] bitcoindevkit/bdk#1115: No update. Still on hold, needs some comment from evan and/or Lloyd. The old method has some problems but it's not clear the impact of it. Degree of complexity (and consequently milestone) needs to be discussed
- [x] bitcoindevkit/bdk#1128: No update. Another approach has to be tried
- [x] bitcoindevkit/bdk#1141: No update. Important to keep it since it affects the Wallet API. Not clear if it is close to end or not
- [x] bitcoindevkit/bdk#979: No update. Related to #1145, so included in alpha.3
#### To Do:
- [x] bitcoindevkit/bdk#1154: discord discussion on scan vs rescan -> since it is related to elecrum, we might take into consideration the electrum naming. Discussion still ongoing, comments on that will be added
- [x] bitcoindevkit/bdk#1153: after discussion on #1139, a new PR needs to be done -> experiment something in the bindings first
- [x] bitcoindevkit/bdk#1144: No update
- [x] bitcoindevkit/bdk#1142: No update. Bug to be investigated before alpha.3 and then evaluate the priority
- [x] bitcoindevkit/bdk#1127: No update

### Milestone TBD:

- [x] bitcoindevkit/bdk#1171: WIP (LagginTimes): shall we assign to beta being it test related? -> put in beta, if it comes earlier we can include it in alpha.3
- [ ] bitcoindevkit/bdk#1072: WIP (evan): is it correct to keep it high priority being it labeled for 2.0 release?
- [x] bitcoindevkit/bdk#1158: should we assign it to beta and then include in alpha.3 if it comes earlier? -> put in beta, if it comes earlier we can include it in alpha.3
- [x] bitcoindevkit/bdk#1176: fixes #1097 -> seems to impact the API, so we assign it to alpha.3 for the moment

## New Projects and Support
- [x] bitcoindevkit/bdk#1165: WIP (einherjar) on ci to Nix -> possibly in the future also for the ffi repo. Put in beta, if it comes earlier we can include it in alpha.3
- [x] bitcoindevkit/bdk#1177: adjustments needed for the release of rust-bitcoin v0.31.0-rc1: not necessary for the 1.0 beta -> put in 2.0 but if we can get it sooner it could be useful
- [x] bitcoindevkit/bdk#1179: discussion ongoing -> useful for android binding, possibly to be included in the next bdk_esplora release. Since it should be quick adding a flag, we added to alpha.3
- [x] bitcoindevkit/rust-esplora-client#61 and bitcoindevkit/rust-esplora-client#66 -> brought by leonardolima, for the moment to 1.1

## Upcoming Events

- [x] [BTC Azores](https://btcazores.com/) Sept 23-24
- [ ] [PlanB Lugano](https://planb.lugano.ch/?lang=it) Oct 20-21

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
