### ISSUE TITLE
W49 Lib Team Call

### ISSUE THREAD

**Issue by nondiremanuel** [bitcoindevkit/.github#87]
:calendar: Tue December 5, 2023 12:00 UTC
:round_pushpin: Discord General Voice Channel

**Please add comments to this issue to suggest issues and PRs to discuss.**

## General Discussion Items

- [ ] BDK 1.0 milestones and timeline: added an alpha.4 milestone to separate the work -> we will try with deadlines every two week
- [ ] BDK Review Club: no review scheduled 
- [ ] Any review begs? :pray: 
- [ ] Blockers? 🪨 

#### Recently merged:
- [x] bitcoindevkit/bdk#1190
- [x] bitcoindevkit/bdk#1204
- [x] bitcoindevkit/bdk#1225
#### Ready to be merged:
- [x] bitcoindevkit/bdk#1179: useful for android binding, possibly to be included in the next bdk_esplora release
#### Need Review:
- [x] bitcoindevkit/bdk#1161: not very high priority, but there are some comments that could need further discussion. If it takes longer, we can move it to alpha.4 -> needs comment by evan / more review
- [x] bitcoindevkit/bdk#1203: needs more discussion, but being pretty important we can leave it to alpha.3 -> discussion ongoing between daniela and evan 
- [x] bitcoindevkit/bdk#1172: review ongoing, some changes were requested -> are all the review comments addressed? Needs a check before merging (and eventually some rebase)
- [x] bitcoindevkit/bdk#1158: needs review (it should be a quick one) -> it will be merged soon
- [x] bitcoindevkit/bdk#1188: improvement on docs -> needs more review
- [x] bitcoindevkit/bdk#1229: new PR -> needs a final review before merging (look if comments have been all addressed)

#### Need Review:
- [ ] bitcoindevkit/bdk#1216: some new commits
- [ ] bitcoindevkit/bdk#1186: no update
- [ ] bitcoindevkit/bdk#1183: needs to wait LDK's https://github.com/lightningdevkit/rust-lightning/pull/2681 before merging, it will be moved back to draft. No update 
- [ ] bitcoindevkit/bdk#1201: no update

#### In Progress
- [ ] bitcoindevkit/bdk#1072: separate repo. Discussion is ongoing
- [x] bitcoindevkit/bdk#1117: still not included in any other PR, we keep it open for the moment, moved to alpha.4
- [x] bitcoindevkit/bdk#1176: seems to impact the API. No update
- [x] bitcoindevkit/bdk#1042: WIP; code already implemented. For now using KeychainKind. No update
- [x] bitcoindevkit/bdk#1115: No update. Still on hold, needs some comment from evan and/or Lloyd. The old method has some problems but it's not clear the impact of it. Degree of complexity (and consequently milestone) needs to be discussed
- [x] bitcoindevkit/bdk#1128: No update. Another approach has to be tried
- [x] bitcoindevkit/bdk#1194: super issue on sync/scan. No update
- [x] bitcoindevkit/bdk#1126: discussion ongoing. No update
- [x] bitcoindevkit/bdk#1175: discussion ongoing. No update
- [x] bitcoindevkit/bdk#1171: no update

#### To Do:
- [ ] bitcoindevkit/bdk#1196: on the upgrade of rust-bitcoin. Unlocked after rust-miniscript release
- [ ] bitcoindevkit/bdk#1233: new issue
- [ ] bitcoindevkit/bdk#1154: should we close this since there is already bitcoindevkit/bdk#1195?
- [x] bitcoindevkit/bdk#1180: it shouldn't be very hard and lower priority for alpha.4
- [x] bitcoindevkit/bdk#1191
- [x] bitcoindevkit/bdk#1199: bug on esplora update local chain
- [x] bitcoindevkit/bdk#1218
- [x] bitcoindevkit/bdk#1221
- [x] bitcoindevkit/bdk#1147
- [x] bitcoindevkit/bdk#797: API breaking
- [x] bitcoindevkit/bdk#1155
- [x] bitcoindevkit/bdk#1038
- [x] bitcoindevkit/bdk#1125
- [x] bitcoindevkit/bdk#1193
- [x] bitcoindevkit/bdk#1103: for now alpha.4, to be discussed -> needs discussion to understand if it's a good idea and how breaking it is going to be

###Milestone TBD
- [x] bitcoindevkit/bdk#1231
- [x] bitcoindevkit/bdk#1230: tests for 1229 (in alpha.3)
- [x] bitcoindevkit/bdk#1227
- [x] bitcoindevkit/bdk#1228: no description to this PR
- [x] bitcoindevkit/bdk#1134: for now alpha.4, to be discussed -> needs to be analyzed and see if it breaks the API or not (if not we can defer it)
- [x] bitcoindevkit/bdk#1219: in 1.1? -> same as 1134

## Other updates for future releases
- [ ] bitcoindevkit/bdk#1223: ready to merge and blocks #1165
- [ ] bitcoindevkit/bdk#1165: ci to Nix; possibly in the future also for the ffi repo. Put in beta, if it comes earlier we can include it in alpha
- [ ] bitcoindevkit/bdk#1120: discussion ongoing
- [ ] bitcoindevkit/bdk#913: brought up by DanGould after long standby
- [x] new [awesome-bdk](https://github.com/thunderbiscuit/awesome-bdk) list

## Upcoming Events
- [ ] Africa Bitcoin Conference (Accra) Dec 1-3 2023

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1

**Comment by thunderbiscuit** [comment]
I'd like to pitch my new [awesome-bdk](https://github.com/thunderbiscuit/awesome-bdk) list for addition to the bitcoindevkit org.
