### ISSUE TITLE
W01 Lib Team Call

### ISSUE THREAD

**Issue by nondiremanuel** [bitcoindevkit/.github#89]
:calendar: Tue January 2, 2024 12:00 UTC
:round_pushpin: Discord General Voice Channel

**Please add comments to this issue to suggest issues and PRs to discuss.**

## General Discussion Items

- [ ] BDK 1.0 milestones and timeline: added an alpha.4 milestone to separate the work -> we will try with deadlines every two week for alphas, then we will evaluate if to extend to once every month (the day after the dev call) -> next release tomorrow afternoon (3rd of Jan)
- [ ] BDK Review Club: no review scheduled 
- [ ] Any review begs? :pray: 
- [ ] Blockers? 🪨 

#### Recently merged:
- [x] bitcoindevkit/bdk#1179
- [x] bitcoindevkit/bdk#1247
- [x] bitcoindevkit/bdk#1158
- [x] bitcoindevkit/bdk#1188
- [x] bitcoindevkit/bdk#1229
- [x] bitcoindevkit/bdk#1183

#### Ready to be merged:
- [x] bitcoindevkit/bdk#1161: needs to be rebased after CI fix, then it can be merged -> needs some more feedback by evan before merging
#### Need Review:
- [x] bitcoindevkit/bdk#1235: review required -> needs some more review and then it's ready to be merged. Lower priority than 1203 and 1172
#### In Progress:
- [x] bitcoindevkit/bdk#1203: needs more discussion (?) and to be rebased, but being pretty important we can leave it to alpha.3 -> in progress but close to be committed. This will ideally be the next merge since it is the biggest one left for alpha.3
- [x] bitcoindevkit/bdk#1172: evan took it over. Needs review -> in progress. Close to be ready (probably tomorrow)

###Milestone TBD
- [x] bitcoindevkit/bdk#1250: alpha.3 or alpha.4? -> alpha.4
- [x] bitcoindevkit/bdk#1234: it is an alternative solution to #1101. The other solution proposed (#1203) is in alpha.3 -> needs another check to see if it can be closed or kept
- [x] bitcoindevkit/bdk#1243: bug on taproot fields -> put in alpha.4 since it seems important
- [x] bitcoindevkit/bdk#1239: discussion on what transactions the function Wallet.transactions() should return -> probably we need more documentation on that, put in alpha.4 in order to have it in sight
- [x] bitcoindevkit/bdk#1245: discussion on design of a block-by-block API -> will be closed when 1172 is merged

## Other updates for future releases
- [x] bitcoindevkit/bdk#1238: on Liquid support. Seems very complicated, postponed -> we leave it open in case someone else wants to comment
- [x] https://github.com/bitcoindevkit/rust-electrum-client/pull/128 -> we are going to define an MSRV for the rust-electrum-client crate

## Upcoming Events
- [x] Africa Bitcoin Conference (Accra) Dec 1-3 2023
- [ ] Bitcoin Atlantis (Funchal, Madera Island) Mar 1-3 2024
- [ ] Bitcoin Seoul (Seoul, South Korea) Apr 26-27 2024

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Core Staging Roadmap]:https://github.com/users/LLFourn/projects/2
[BDK 1.0]:https://github.com/orgs/bitcoindevkit/projects/14
[BDK Maintenance]: https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7
[Documentation Roadmap]:https://github.com/orgs/bitcoindevkit/projects/9
[BDK Core Project]:https://github.com/users/LLFourn/projects/2/views/1
