### ISSUE TITLE
W26 BDK Library Team Call

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/.github#9]
# W26, BDK Library Dev Call
:calendar: Tues June 21, 2022 13:00 UTC
:round_pushpin: Discord General Voice Channel 

## Discussion Items

- [x] BDK 0.19.0 with tr() support Released! :carrot: 
    - Raj: try min.sc for testing
- [x] Plebfi LA recap
- [x] Raj BDK Demo in Nov in India
- [x] Any review begs? :pray:
    - thunderbiscuit: bdk-python update to latest bdk
- [x] Blockers? 🪨

## New Projects and Support

- [Fedimint](https://github.com/fedimint) tweeked key descriptor wallet

## Top BDK PRs and issues

- [x] 🎯 [BDK Roadmap]
- [x] Avoid using immature coinbase inputs
[#614](https://github.com/bitcoindevkit/bdk/pull/614)
- [x] Add remove_partial_sigs and try_finalize to SignOptions [#621](https://github.com/bitcoindevkit/bdk/pull/621)
- [x] Add support for custom sorting and deprecate BIP69 [#556](https://github.com/bitcoindevkit/bdk/pull/556)
- [x] BIP39 implementation [#607](https://github.com/bitcoindevkit/bdk/pull/607)
- [x] Add extended descriptor multisig metadata to policy extraction [#626](https://github.com/bitcoindevkit/bdk/pull/626)
- [x]  Add waste metric for coin selection [#558](https://github.com/bitcoindevkit/bdk/pull/558)
    - depends on [#630](https://github.com/bitcoindevkit/bdk/pull/630)

## Top BDK_CLI PRs and issues

- [x] 🎯 [BDK-CLI Roadmap]
    - priorities for future releases: 
        1. update to bdk 0.19 and cli code reorg
        2. embedded bitcoind regtest control
        3. regtest integration tests
- [x]  The Great Reset [#99](https://github.com/bitcoindevkit/bdk-ffi/pull/99)

<br>

🌅 *[Future Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aopen)*

📜 *[Past Call Notes](https://github.com/bitcoindevkit/.github/issues?q=label%3ACall+is%3Aclosed)*

[BDK Milestones]:https://github.com/bitcoindevkit/bdk/milestones
[BDK Roadmap]:https://github.com/orgs/bitcoindevkit/projects/6
[BDK-CLI Roadmap]:https://github.com/orgs/bitcoindevkit/projects/7#
